services:
  mediawiki:
    image: mediawiki
    ports:
      - "8085:80"
    volumes:
      - mediawiki_data:/var/www/html
    restart: always

  nextcloud:
    image: nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_HOST: nextcloud_mysql
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: nextcloud_password
    restart: always

  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "4444:80"
    volumes:
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:4444'
        gitlab_rails['db_adapter'] = 'mysql2'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'gitlab_mysql'
        gitlab_rails['db_port'] = '3306'
        gitlab_rails['db_username'] = 'root'
        gitlab_rails['db_password'] = 'your_gitlab_mysql_root_password'
    restart: always

  nextcloud_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_nextcloud_mysql_root_password
    volumes:
      - nextcloud_mysql_data:/var/lib/mysql
    restart: always

  gitlab_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_gitlab_mysql_root_password
    volumes:
      - gitlab_mysql_data:/var/lib/mysql
    restart: always

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  mediawiki_data:
  nextcloud_data:
  gitlab_data:
  nextcloud_mysql_data:
  gitlab_mysql_data:
