services:
  mediawiki:
    image: mediawiki
    ports:
      - "8085:80"
    volumes:
      - mediawiki_data:/var/www/html
    restart: always

  nextcloud:
    image: nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    restart: always

  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "4444:80"
    volumes:
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:4444'
        gitlab_rails['db_adapter'] = 'mysql2'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'mysql'
        gitlab_rails['db_port'] = '3306'
        gitlab_rails['db_username'] = 'FloClauTer'
        gitlab_rails['db_password'] = 'MirHoleDe5er'
    restart: always

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  mediawiki_data:
  nextcloud_data:
  gitlab_data:
  mysql_data: